### ISSUE TITLE
Project's License

### ISSUE THREAD

**Issue by muriloime** [soun059/SpokenLanguageAssessment#1]
Hello @soun059 , 

first of all, congratulations on the project! It seems very promising!
 
I am intending to dig a little deeper, but  I would like first to understand the license of the code. Would you mind updating the license terms ?

Thanks a lot
Murilo

**Comment by soun059** [comment]
Dear Sir,
I am so much happy to get a reply from you! I really liked your work and wanted to improve certain aspects of the work so it can have much features. I am really a bit of new in GitHub policies and licensing... Can you please guide me what should I do for this? Definitely waiting to listen from you Sir!
